### ISSUE TITLE
Rebase snap on new go version

### ISSUE THREAD

**Issue by bernermic** [cheat/snap#5]
Hi @chrisallenlane,

I rebased and build and released the snap version on cheat 3.2.1. 
To get the build working for all architectures I used peaces of your [shellscript](https://github.com/cheat/cheat/blob/master/bin/build_release.sh). 

I tested the amd64 and arm64 version and it looks fine to me.

One thing which is not so nice currently - if the personal cheatpath is not given one get's in the errormessage:
```
$ cheat
failed to load config: failed to resolve symlink: , lstat /home/ubuntu/snap/cheat/1300/.cheat: no such file or directory
```
Would it not be more convinient to tell the user to create this directory by providing the command in the message?
This `/home/ubuntu/snap/cheat/1300/` is the Snap's view on the user's cheat home dir. The symlink is this: `/home/ubuntu/snap/cheat/current/` and current is a symlink to the snap version 1300.

In the same direction goes this: I think it would be nice to give the user a clear message when initially no editor is set:
```
$ cheat
failed to load config: no editor set
```
would be more convinient with something like this:
`failed to load config: $EDITOR or $VISUAL not set. Please configure environment variable.`

What do you think about this?

Greetings
Michael

**Comment by chrisallenlane** [comment]
Hi, @bernermic 

Thanks, as always, for your work on this.

Yeah, the messaging in `cheat` is somewhat poor right now. We have a thread going on about this over here: https://github.com/cheat/cheat/issues/501

I haven't had time to work on this much recently (I've been quite busy with work and the holidays), but - with luck - we can expect some improvements to land in this area sometime early next year.
