### ISSUE TITLE
Unclear first run/configuration steps

### ISSUE THREAD

**Issue by MakisH** [cheat/snap#9]
I am trying to install cheat on Ubuntu 20.10, but I am stuck at the following situation:

```shell
~$ cheat
A config file was not found. Would you like to create one now? [Y/n]:
Would you like to download the community cheatsheets? [Y/n]:
warning: unable to access '/etc/gitconfig': Permission denied
warning: unable to access '/etc/gitconfig': Permission denied
fatal: unknown error occurred while reading the configuration files
failed to create config: failed to clone cheatsheets: exit status 128
```
And I get the same with `sudo`.

The `README.md` states:
```
$ snap install cheat
$ cheat.cheatsheet-setup
```
However, `cheat.cheatsheet-setup` is not found on my Ubuntu 20.10 and I don't understand where it should come from. Should it be included in the snap package?

I am really confused on how I should configure/run cheat for the first time. I expected that `snap install cheat` automatically installs also the default cheatsheets and configures cheat, but maybe I am doing something wrong.

Probably related (regarding the reasons behind this issue): #6 

(btw, thanks a lot for making this amazing tool, it is very helpful! :beer:)

**Comment by bernermic** [comment]
Hey @MakisH ,

sorry for late answer and thanks for your remark.

The documentation was outdated, but now is in an accurate state again. I close this issue now.

Greetings
